stps:
  - stp_id: my_stp1                  # Required, str, Uniq ID of the STP.
    port_id: 1/1/51                # Required, str, ID of the corresponding port.
    vlans: "1779-1799"                    # Required, str, VLANs part of this STP.
    description: "Dell STP test 1"         # Optional, str, STP description.
    is_alias_in: "urn:ogf:network:twaren.nchc.org:2014:topology:starlight-out"         # Optional, str, Inbound STP ID from connected topology.
    is_alias_out: "urn:ogf:network:twaren.nchc.org:2014:topology:starlight-in"        # Optional, str, Outbound STP ID to connected topology.
    bandwidth: 1000   # Required, int, Available bandwidth for this STP in Mbps.
    enabled: True          # Optional, bool, STP status.

  - stp_id: my_stp2
    port_id: 1/1/52
    vlans: "1779-1799"
    description: "Dell STP test 2"
    bandwidth: 1000   # Required, int, Available bandwidth for this STP in Mbps.
    enabled: True          # Optional, bool, STP status.
