apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "SuPA.fullname" . }}-{{ .Values.config.name }}
#  namespace: {{ .Release.Namespace }}
data:
{{ range $path, $_ :=  .Files.Glob  .Values.config.filesGlob }}
{{ $path | base | indent 2 }}: |-
{{ $.Files.Get $path | b64enc | indent 4 }}
{{ end }}
