stps:
  - stp_id: my_stp2                  # Required, str, Uniq ID of the STP.
    port_id: ethernet2                  # Required, str, ID of the corresponding port.
    vlans: "1728"                    # Required, str, VLANs part of this STP.
    description: "my test stp 2."         # Optional, str, STP description.
    is_alias_in: my_stp2         # Optional, str, Inbound STP ID from connected topology.
    is_alias_out: my_stp2        # Optional, str, Outbound STP ID to connected topology.
    bandwidth: 1000   # Required, int, Available bandwidth for this STP in Mbps.
    enabled: True          # Optional, bool, STP status.

  - stp_id: my_stp3
    port_id: ethernet3
    vlans: "1728-1735"
    description: "my test stp 3."
    is_alias_in: my_stp3
    is_alias_out: my_stp3

  - stp_id: my_stp4
    port_id: ethernet4
    vlans: "1728-1735"
    description: "my test stp 4."
    is_alias_in: my_stp4
    is_alias_out: my_stp4

  - stp_id: openstp
    port_id: ethernet5
    vlans: "1779-1799"
    description: "STP for icair test."
    is_alias_in: openstp-in
    is_alias_out: openstp-out

  - stp_id: mren8700
    port_id: et49/1
    vlans: "1779-1799"
    description: "STP to iCAIR OpenNSA mren8700 ar100 for icair onsa test."
    is_alias_in: "icair.org:2013:mren8700:ar100-in"
    is_alias_out: "icair.org:2013:mren8700:ar100-out"
