stps:
  # Bidirectional STP with directional endpoints
  - stp_id: my_stp
    port_id: ethernet2
    vlans: "1728"
    description: "Arista STP to StarLight"
    remote_stp_in:
      prefix_urn: "urn:ogf:network:twaren.nchc.org:2014:topology"
      id: "starlight-out"
    remote_stp_out:
      prefix_urn: "urn:ogf:network:twaren.nchc.org:2014:topology"
      id: "starlight-in"
    bandwidth: 1000
    enabled: True

  # STP for mren8700 with directional endpoints
  - stp_id: mren8700
    port_id: et49/1
    vlans: "1779-1799"
    description: "STP to iCAIR OpenNSA mren8700 ar100"
    remote_stp_in:
      prefix_urn: "icair.org:2013:mren8700"
      id: "ar100-out"
    remote_stp_out:
      prefix_urn: "icair.org:2013:mren8700"
      id: "ar100-in"
    bandwidth: 1000
    enabled: True
