name: gh-pages
on:
  push:
    branches:
      - master
jobs:
    publish-docs:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
            with:
              python-version: 3.8

          - run: pip install -e '.[dev,doc]'
          - run: bash update_docs_github.sh

