name: Unit tests
on: push

jobs:
  container_job:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8.12 ]
    container: python:${{ matrix.python-version }}-slim
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl git
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          python setup.py gen_code
      - name: Run Unit tests
        run: pytest --cov-report term-missing --cov-report=xml --cov=src tests
              -k "not activate_job_end_date and not activate_job_no_end_date and not deactivate_job and not release_job_release_confirmed_auto_end"
              # Exclude test targets in "test_dataplane.py" and "test_provision.py" that require a backend device when calling backend's de/activate().
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true
